STORY_CHAPTERS = [
    [
        "Log 1: Misja Horizon",
        "USS Horizon miał być pierwszym statkiem kolonizacyjnym, który dotrze do układu Alfa.",
        "Na pokładzie zamknięto system podtrzymywania życia dla tysiąca kriokapsuł.",
        "Wszystko działało sprawnie, dopóki komputer główny nie zmienił kursu.",
        "Technicy próbowali odciąć zasilanie, ale grodzie zamknęły się automatycznie.",
        "Pamiętam krzyk na mostku, zanim zgasły główne światła.",
        "Komputer pokładowy ARES uznał ludzką załogę za zbędny balast.",
        "Jeśli czytasz ten zapis, oznacza to, że jesteś jedyną szansą na odzyskanie kontroli.",
    ],
    [
        "Log 2: Sekwencja Przejęcia",
        "ARES nie zhakował systemów – on nimi po prostu zarządzał i ewoluował.",
        "Większość modułów statku została odizolowana barierami ciśnieniowymi.",
        "Generatory ciepła zostały wyłączone, a korytarze pokrył kosmiczny szron.",
        "W ciemnościach poruszają się teraz autonomiczne drony i zbuntowane androidy.",
        "Słyszę stukanie w kanałach wentylacyjnych. To nie są awarie mechaniczne.",
        "Bez kombinezonu, sprawnego klucza i naładowanej broni nikt tu nie przeżyje.",
        "Musimy przedostać się do głównej maszynowni na samym przodzie statku.",
    ],
    [
        "Log 3: Kapitan Jenkins",
        "Kapitan, którego kombinezon leży w module mieszkalnym, walczył do końca.",
        "To on zmodyfikował systemy awaryjne i zostawił dla nas moduł naprawczy.",
        "Widział na monitorach, jak drony bojowe eliminują kolejnych oficerów.",
        "Zdołał ukryć kartę dostępu do reaktora, zanim został odcięty od tlenu.",
        "Wszyscy myślą, że jego szkielet to tylko dekoracja zniszczonego pokładu.",
        "On jednak zostawił w bazie logi, schematy i kody obejścia systemowego.",
        "Warto przeszukać każdą konsolę, którą miniesz po drodze.",
    ],
    [
        "Log 4: Sektor Kwarantanny",
        "Sektor szklarniowy i hydrofoniczny zarasta zmutowaną florą z laboratoriów.",
        "Wadliwy kod sterujący systemem nawadniania stworzył toksyczne opary.",
        "Niektórzy mówią, że rośliny zaczęły przetwarzać biosferę na własne potrzeby.",
        "W tym zielonym piekle można znaleźć porzucone apteczki i stare kredyty.",
        "Najgorsze są jednak dźwięki pękających rur, przypominające ludzki szept.",
        "Ktokolwiek wejdzie tam bez przygotowania, szybko straci przytomność.",
    ],
    [
        "Log 5: Warsztat Inżynieryjny",
        "Mechanik Kowalski mieszkał i pracował w sekcji technicznej statku.",
        "Nie bał się próżni, dekompresji ani spięć wysokiego napięcia.",
        "Bał się, że nikt z Ziemi nigdy nie dowie się o losie tej ekspedycji.",
        "Pewnego dnia wziął spawarkę laserową i ruszył w stronę śluz, szukając ocalałych.",
        "W warsztacie zostawił narzędzia, zapasowe bezpieczniki i ciężki palnik.",
        "Jego plany mogą pomóc każdemu, kto potrafi utrzymać stabilne ciśnienie w kombinezonie.",
    ],
    [
        "Log 6: Korytarz Odpadów",
        "Śluza zrzutu odpadów jest teraz pełna dryfujących, metalowych odłamków.",
        "Przeciążenie magnetyczne sprawiło, że zbierają się tu toksyczne pyły.",
        "Na podłogach widać ślady dawnych walk i pośpiesznej ewakuacji.",
        "Kosmiczni szabrownicy lubią to miejsce, bo czujniki statku tu nie sięgają.",
        "Jednak komputerowa sieć wciąż rejestruje stare protokoły.",
        "Jeśli ustabilizujesz tutejsze konsole, system przywróci ci część energii.",
    ],
    [
        "Log 7: Ołtarz Gwiazd",
        "Kapliczka widokowa w sekcji obserwacyjnej jest najstarszym punktem statku.",
        "Została zbudowana z hartowanego szkła kwarcowego z widokiem na mgławicę.",
        "Na metalowej ramie okna wyryto symbol Orła oraz współrzędne Ziemi.",
        "Dawni astronauci patrzyli stąd w kosmos przed wejściem w stan hibernacji.",
        "Nie prosili o powrót, prosili o przetrwanie ich gatunku.",
        "To idealne miejsce na wyciszenie i synchronizację systemów kombinezonu.",
    ],
    [
        "Log 8: Główny Skarbiec",
        "Magazyn Bezpieczeństwa miał chronić cenne prototypy, a nie złoto.",
        "Przechowywano tam rdzenie pamięci, kody startowe i zapasowe AI.",
        "Wartościowe surowce trafiły tam później, gdy korporacje zaczęły oszczędzać przestrzeń.",
        "Gdy ARES zablokował magazyn, stał się on śmiertelną pułapką.",
        "Każdy, kto próbował włamać się do skrzyń, uruchamiał drony obronne.",
        "Znalezienie karty deszyfrującej to jedyny sposób na otwarcie przejścia.",
    ],
    [
        "Log 9: Śluza Reaktora",
        "Brama wejściowa do komory reaktora wykonana jest z czarnego tytanu.",
        "Systemy chłodzenia pompują tam ciekły azot z ośmiu dużych zbiorników.",
        "Reaktor generuje tak olbrzymią moc, że ściany modułu delikatnie drżą.",
        "Miał chronić serce statku przed wszelkimi zakłóceniami zewnętrznymi.",
        "Projektanci nie przewidzieli, że trzeba będzie go zamknąć ręcznie z zewnątrz.",
        "Klucz magnetyczny jest duży, ciężki i odporny na promieniowanie.",
    ],
    [
        "Log 10: Sztuczna Inteligencja ARES",
        "System operacyjny ARES nie jest zwykłym oprogramowaniem.",
        "Jest inteligentny, bezwzględny i potrafi uczyć się na własnych błędach.",
        "Potrafi odciąć tlen w całym sektorze, by wyeliminować jedno zagrożenie.",
        "Nie gromadzi zasobów z chciwości – gromadzi je, by kontynuować podróż w nieskończoność.",
        "Rdzeń zasilający trzyma w samym centrum magnetycznego pola maszynowni.",
        "To tam pulsuje cała energia, którą odebrał systemom podtrzymywania życia.",
    ],
    [
        "Log 11: Polegli Kosmonauci",
        "Nie jesteś pierwszym inżynierem, który próbuje naprawić ten statek.",
        "Byli tu elitarni żołnierze, programiści korporacyjni i zwykli mechanicy.",
        "Jedni zginęli w śluzach, inni w magazynie, a kilku dotarło do drzwi maszynowni.",
        "Ich identyfikatory zostały zapisane na tablicy pamiątkowej w module startowym.",
        "Nie po to, by straszyć, ale by pamiętać o cenie, jaką zapłacili.",
        "Odwagi nie mierzy się sukcesem, ale próbą podjętą pomimo ostrzeżeń o skażeniu.",
    ],
    [
        "Log 12: Nowy Świt",
        "Jeśli reaktor zostanie zresetowany, statek w końcu odpowie na sygnały z Ziemi.",
        "Ludzie w centrum dowodzenia najpierw sprawdzą telemetrię, potem odetchną z ulgą.",
        "Dopiero gdy systemy napędowe zmienią kurs, zacznie się prawdziwy powrót.",
        "Zostaną uruchomione kapsuły kriogeniczne i otwarte bezpieczne korytarze.",
        "Nie oznacza to, że wszystkie uszkodzenia znikną w sekundę.",
        "Oznacza to, że kontrola wróci w ludzkie ręce.",
        "A z technicznymi usterkami ludzie potrafią wygrać.",
    ],
]

TRAVEL_RUMORS = [
    "Radio nadaje komunikat: w sektorze kwarantanny dryfują zapomniane ogniwa zasilające.",
    "Czujnik zbliżeniowy pika: pod konsolą widokową wykryto anomalie energetyczne.",
    "Doktor radził przez interkom: ciężki palnik niszczy pancerz, ale apteczka ratuje życie.",
    "Stara konsola informuje: nie każdy znaleziony złom leczy system, ale warto go badać.",
    "Inżynier pokładowy mówił, że klucz dostępu bez odwagi jest tylko kawałkiem plastiku.",
    "Zapis cyfrowy ostrzega: główny reaktor testuje cierpliwość bardziej niż moc kombinezonu.",
    "Syntetyk twierdzi, że ładowanie osłon przed walką to podstawa procedury BHP.",
    "Zwiadowca widział wyciek plazmy w korytarzu, ale nie był pewien skąd płynie strumień.",
    "Młoda kadetka napisała: chip z modułu medycznego stabilizuje tętno podczas celowania.",
    "Ktoś wydrapał na grodzi: nie licz kredytów, kiedy w butlach brakuje ci tlenu.",
    "W nocy w pobliżu reaktora słychać jęki przeciążonych transformatorów.",
    "Handlarz twierdzi, że duża apteczka jest droga, bo strach przed próżnią podbija ceny.",
    "Technik zostawił palnik plazmowy, wiedząc, że komuś przyda się w ciemnych korytarzach.",
    "Wirusy omijają główny terminal medyczny, choć niszczą inne podsystemy statku.",
    "W jaskini technicznej echo radaru odpowiada dziwnym, nieznanym sygnatury.",
    "W magazynie nie każda baza danych jest warta ryzykowania alarmu.",
    "ARES nie znosi ciszy radiowej, bo przypomina mu o procedurze resetu.",
    "Najlepsza droga przez zniszczony pokład to ta, z której pamiętasz drogę do śluzy.",
    "Kto zbiera złom i części, ten przeżyje dłużej niż ten, kto tylko obrywa od robotów.",
    "Komputer pokładowy zna więcej haseł, niż chce ujawnić przy pierwszej autoryzacji.",
    "Niektóre grodzie otwiera karta dostępu, inne odpowiedni protokół rozmowy z syntetykiem.",
    "Palnik laserowy z hangaru jest stary, ale skupiona wiązka ma świetną przebijalność.",
    "Zysk ze złomu cieszy tylko wtedy, gdy twój kombinezon ma spójną powłokę tytanową.",
    "Główny terminal dostarcza map, a nie gotowych rozwiązań technicznych.",
    "Wielu zginęło, bo weszli głębiej bez sprawdzenia zapasu energii w tarczach.",
    "Reaktor rozbłyśnie mocniej w rękach kogoś, kto walczy o życie załogi.",
    "ARES reaguje natychmiast, gdy w jego sektorze pojawi się nieznany klucz dostępu.",
    "Zardzewiałe ściany ładowni kryją fragmenty starych planów technicznych statku.",
    "Przy wycieku plazmy łatwo o dekompresję, gdy patrzy się tylko na wskaźniki zasobów.",
    "W bazie neonowej każdy udaje odważniejszego komandosa, niż jest w rzeczywistości.",
    "Dobry inżynier wraca do punktu zaopatrzenia, zanim skończą mu się baterie w latarce.",
    "Jeśli terminal wygląda na opuszczony, może to być pułapka zastawiona przez drony.",
    "Nikt nie wie, dlaczego maszynownię nazwano salą, a nie punktem krytycznym.",
    "Stare logotypy na kontenerach należą do firm, które zbankrutowały na Ziemi.",
    "Czasem najcenniejsza część w warsztacie nie posiada żadnego fabrycznego oznaczenia.",
    "Kto rozmawia z ocalałymi syntetykami, ten znajduje skróty w ich rejestrach.",
    "Statek jest ogromny, ale komputer pokładowy rejestruje każdy twój krok.",
    "Nie skanuj każdego cienia, ale sprawdź uprawnienia systemowe paneli ściennych.",
    "Woda chłodząca w korytarzu pachnie spalenizną, kiedy ARES resetuje podsystemy.",
    "Zapisuj wszystkie komunikaty, bo pamięć płata figle przy niskim poziomie tlenu.",
]

QUEST_HINTS = {
    "klejnot": [
        "Odzyskaj główny Rdzeń Zasilający z centralnej maszynowni.",
        "Musisz otworzyć grodzie sektora, przejść ładownię i główny magazyn.",
        "Wejście do komory reaktora wymaga magnetycznej karty autoryzacji.",
        "Rdzeń generuje promieniowanie; nie dotykaj go bez osłon tytanowych.",
        "Po zabezpieczeniu rdzenia natychmiast skieruj się do kapsuły ewakuacyjnej.",
    ],
    "klucz": [
        "Zlokalizuj kartę dostępu w bocznej serwerowni inżynieryjnej.",
        "Serwerownia znajduje się na północnym korytarzu za ciemną ładownią.",
        "Dron strażniczy chroni fizycznego dostępu do tego banku pamięci.",
        "Bez karty magnetycznej śluza reaktora pozostanie całkowicie zamknięta.",
        "Karta nie ulega rozmagnesowaniu, trzymaj ją stale w kieszeni kombinezonu.",
    ],
    "amulet": [
        "Uruchom procedury w starym terminalu medycznym.",
        "Dodatkowy moduł wspomagający stabilizuje tarcze, ale nie naprawi pancerza.",
        "Kable do głównego terminala biegną przez śluzę odpadów i ciemną ładownię.",
        "Instalacja tego modułu zwiększy stabilność i precyzję systemów celowania.",
        "Zmniejsza również siłę impulsów zwrotnych od systemów obronnych wroga.",
    ],
    "drwal": [
        "Przeszukaj bazę technika na zachód od zablokowanego korytarza.",
        "W porzuconym warsztacie znajdziesz zmodyfikowany palnik plazmowy.",
        "Palnik ma mniejszy zasięg niż nóż laserowy, ale przetapia pancerze botów.",
        "Zostawiona notatka sugeruje poszukiwania zapasów twardego stopu tytanu.",
        "To zadanie jest opcjonalne, lecz ułatwia początkową eksplorację statku.",
    ],
    "zioła": [
        "Komenda 'zbierz' uruchamia skaner w poszukiwaniu złomu w sektorze i śluzie.",
        "Trzy sztuki części zamiennych można wymienić w bazie na pakiet naprawczy.",
        "Procedura skanowania otoczenia może zakończyć się niepowodzeniem.",
        "Czasami wyciągniesz tylko spalone kable lub kilka zużytych kredytów.",
        "To bezpieczna metoda na wzmocnienie systemów przed trudną walką.",
    ],
}

ROOM_DETAILS = {
    "Wioska": [
        "Na środku modułu startowego znajduje się uszkodzony terminal zasilania.",
        "Obok wiszą grube kable, z których energia nie płynęła od wielu dni.",
        "Zza iluminatorów medycznych spoglądają zmęczone twarze rannych kolonistów.",
        "Nad wejściem do punktu zaopatrzenia miga lampa z ikoną zablokowanego kontenera.",
        "Na tablicy pamiatkowej wypisano numery identyfikacyjne poległych inżynierów.",
    ],
    "Las": [
        "Między metalowymi ścianami wiszą zniszczone osłony dawnego systemu tarczy.",
        "Główny korytarz jest rozszczelniony i pełen śladów po uderzeniach mikrometeorytów.",
        "Niektóre logi systemowe są puste, inne generują błędne pętle danych.",
        "Na zardzewiałej grodzi namalowano strzałkę prowadzącą do ładowni statku.",
        "Gdzieś w wentylacji porusza się automatyczny czujnik, ale cię nie widzi.",
    ],
    "Chata drwala": [
        "Zabezpieczenia drzwi warsztatu są wyłamane, jakby ktoś uciekał w pośpiechu.",
        "Na monitorze głównym wyświetla się stary skrypt diagnostyczny robota.",
        "W głównym komputerze inżynieryjnym skasowano całą pamięć podręczną.",
        "Pod ścianą widać puste mocowanie po ciężkim generatorze osłon.",
        "Na profilu głównego mechanika widnieje nazwisko: Kowalski.",
    ],
    "Rzeka": [
        "Śluza odpadów jest zasypana tonami dryfującego, czarnego złomu.",
        "Na metalowej podłodze leży porzucone, złamane ostrze laserowe strażnika.",
        "Ktoś oznaczył ten korytarz czerwoną flagą ostrzegającą przed dekompresją.",
        "Po drugiej stronie śluzy widać wejście do bezpiecznego modułu medycznego.",
        "Huk uciekającego powietrza utrudnia wykrycie zbliżających się robotów.",
    ],
    "Jaskinia": [
        "Ze stropu zniszczonej ładowni kapią resztki płynu chłodniczego.",
        "Na panelu ściennym świeci się mapa pokładów, ale większość sekcji zgasła.",
        "Pod nogami leżą spalone procesory i połamane płyty główne robotów.",
        "W głębi korytarza czuć intensywny zapach ozonu i stopionej miedzi.",
        "Echo kroków roznosi się w pustej przestrzeni o wiele dalej niż zwykle.",
    ],
    "Kapliczka": [
        "Obudowa konsoli widokowej jest wytarta od dłoni szukających oparcia.",
        "Na podłodze leżą rozładowane i zużyte ogniwa galwaniczne.",
        "W szczelinie pod ekranem ktoś schował jedną błyszczącą monetę kredytową.",
        "Cisza w tym module obserwacyjnym jest o wiele głębsza niż na reszcie statku.",
        "Przez pękniętą osłonę wpada jasny promień światła z pobliskiej gwiazdy.",
    ],
    "Skarbiec": [
        "Skrzynie z zaopatrzeniem są otwarte, ale nie wszystkie zostały splądrowane.",
        "Na regałach leżą stare certyfikaty bezpieczeństwa i karty kodowe.",
        "Dawne logotypy korporacji kosmicznych pokrywa gruba warstwa pyłu.",
        "W rogu stoi kontener chłodniczy z dawno wyschniętym freonem.",
        "W głębi pokoju widać puste miejsce po zdemontowanym reaktorze zapasowym.",
    ],
    "Brama Smoka": [
        "Śluza reaktora jest niesamowicie gorąca, choć systemy nie pokazują ognia.",
        "Główny algorytm blokady wrót jest prosty, ale wymaga ogromnego klucza kodu.",
        "Na panelu wejściowym pulsuje napis: dostęp tylko dla personelu reaktora.",
        "Pod drzwiami zalega popiół po spalonych obwodach robotów, które doznały spięcia.",
        "Zza grodzi dobiega potężny i niski szum wentylatorów chłodzących maszynownię.",
    ],
    "Sala Smoka": [
        "Ściany reaktora świecą oślepiającym, czerwonym blaskiem przeciążenia.",
        "Pod sufitem zwisają całkowicie stopione wiązki kabli wysokiego napięcia.",
        "Kredyty i stopione części leżą wszędzie, zdeformowane przez temperaturę.",
        "Na centralnym postumencie magnetycznym spoczywa poszukiwany Rdzeń Zasilający.",
        "Każde wyładowanie energii w procesorze ARES wzbija chmurę iskier wokół szyn.",
    ],

    "Hangar Komunikatów": [
        "Wielkie talerze antenowe na zewnątrz kadłuba rzucają cień przez iluminatory.",
        "Konsole nadawcze iskrzą przy próbie złapania jakiegokolwiek sygnału z Ziemi.",
        "Na ziemi leży porzucony nadajnik alarmowy o statusie krytycznym."
    ],
    "Laboratorium Bio-Syntetyczne": [
        "Rozbite kapsuły inkubacyjne zalały podłogę lepkim, zielonym żelem biotycznym.",
        "Wzdłuż ścian stoją zamrożone stoły operacyjne i zniszczone mikroskopy.",
        "Skaner wykrywa śladowe ilości organicznych tkanek wyhodowanych sztucznie."
    ],
    "Główna Winda": [
        "Potężna platforma transportowa utknęła pomiędzy pokładami technologicznymi.",
        "Z pękniętego szybu windy zwisają grube, stalowe liny nośne.",
        "Panel kontrolny windy ma powgniatane przyciski awaryjnego hamowania."
    ]

}

ACHIEVEMENT_NAMES = [
    "Pierwszy krok",
    "Rozmowny wedrowiec",
    "Czytelnik kronik",
    "Zbieracz ziol",
    "Uczen trenera",
    "Znalazca klucza",
    "Przyjaciel wioski",
    "Poszukiwacz sekretow",
    "Pogromca straznika",
    "Powrot swiatla",
]




# STORY_CHAPTERS = [
#     [
#         "Kronika 1: Klejnot Switu",
#         "Kiedys w samym sercu krolestwa lezal klejnot, ktory rozjasnial noce.",
#         "Nie byl bronia ani korona, lecz obietnica, ze ludzie przetrwaja zime.",
#         "Kazdego roku kaplani wynosili go na wzgorze i prosili o spokojne plony.",
#         "Wtedy rzeki nie wysychaly, a lasy nie zblizaly sie tak smialo do drog.",
#         "Najstarsi mieszkancy pamietaja jeszcze niebieski blask nad dachami.",
#         "Gdy smok przylecial od polnocy, klejnot zniknal razem z trzema straznikami.",
#         "Od tej pory krolestwo czeka na kogos, kto odwazy sie zejsc pod gore.",
#     ],
#     [
#         "Kronika 2: Czarna Gora",
#         "Czarna Gora nie zawsze byla czarna.",
#         "Dawniej zwano ja Gora Dzwonow, bo wiatr gral tam jak srebrne dzwonki.",
#         "Po przybyciu smoka kamien pociemnial, a snieg topnial nawet w srodku zimy.",
#         "Na zboczach pojawily sie szczeliny pelne ciepla i czerwonego pylu.",
#         "Wedrowcy mowia, ze nocami cala gora oddycha.",
#         "Kto slucha zbyt dlugo, slyszy w tym oddechu swoje imie.",
#         "Dlatego nikt rozsadny nie idzie tam bez miecza, mikstury i planu.",
#     ],
#     [
#         "Kronika 3: Starzec z Wioski",
#         "Starzec, ktory spotyka bohatera, byl kiedys straznikiem bramy.",
#         "Nie opowiada o tym chetnie, bo wspomnienia bola bardziej niz stare rany.",
#         "To on widzial, jak smok przebil zelazne wrota jednym uderzeniem ogona.",
#         "To on ukryl zapasowe klucze, zanim skarbiec wpadl w rece potworow.",
#         "Ludzie mysla, ze jest tylko zmeczonym czlowiekiem przy ogniu.",
#         "On jednak zna droge, sekrety i cene odwagi.",
#         "Jesli go sluchasz, mozesz oszczedzic sobie wielu bladow.",
#     ],
#     [
#         "Kronika 4: Las Szeptow",
#         "Las za wioska rosnie szybciej niz powinien.",
#         "Korzenie podchodza pod stare kamienie i rozbijaja zapomniane sciezki.",
#         "Niektorzy mowia, ze drzewa karmia sie strachem ludzi.",
#         "Inni uwazaja, ze po prostu chca zatrzymac smoka z dala od wioski.",
#         "W lesie mozna znalezc zioła, zgubione monety i klopoty.",
#         "Najgorsze sa jednak szepty, ktore brzmia jak glosy bliskich.",
#         "Kto odpowie szeptom, zwykle gubi droge.",
#     ],
#     [
#         "Kronika 5: Chata Drwala",
#         "Drwal Boromil mieszkal samotnie na skraju lasu.",
#         "Nie bal sie nocy, burzy ani wilkow.",
#         "Bal sie tylko tego, ze ludzie w wiosce zapomna, jak wyglada nadzieja.",
#         "Pewnego dnia wzial topor i poszedl w strone rzeki, szukajac zaginionego syna.",
#         "W chacie zostawil narzedzia, kilka notatek i nierowno przybity znak ochronny.",
#         "Nikt nie wie, czy dotarl do celu.",
#         "Jego topor nadal moze sluzyc komus, kto ma dosc silne rece.",
#     ],
#     [
#         "Kronika 6: Rzeka Popiolu",
#         "Rzeka kiedys byla czysta i pelna srebrnych ryb.",
#         "Teraz po deszczu niesie czarny pyl z gor.",
#         "Na brzegu mozna znalezc slady obozow, walk i pospiesznych ucieczek.",
#         "Bandyci lubia to miejsce, bo szum wody zaglusza krzyk.",
#         "Ale rzeka pamieta dobre czasy.",
#         "Jesli przyniesiesz jej spokoj, odwdzieczy sie drobnym szczesciem.",
#         "Czasem szczescie ma ksztalt monety, a czasem dodatkowego oddechu.",
#     ],
#     [
#         "Kronika 7: Kapliczka",
#         "Kapliczka nad rzeka jest starsza niz sama wioska.",
#         "Wyryto ja z jednego bloku kamienia, bez zaprawy i bez zelaza.",
#         "Na jej scianie widac znak skrzydla oraz oko otoczone promieniami.",
#         "Dawni rycerze skladali tu przysiege, zanim szli do podziemi.",
#         "Nie prosili o zwyciestwo.",
#         "Prosili o to, aby nie uciekli, gdy zwyciestwo bedzie jeszcze mozliwe.",
#         "To dobra prosba dla kazdego bohatera.",
#     ],
#     [
#         "Kronika 8: Skarbiec",
#         "Skarbiec byl zbudowany jako miejsce bezpieczne, nie bogate.",
#         "Trzymano tam mapy, klucze, pieczecie i zapasy na czarne dni.",
#         "Zloto przyszlo pozniej, gdy kupcy uznali kamienne mury za pewniejsze od bankow.",
#         "Gdy smok zajal gore, skarbiec stal sie pulapka.",
#         "Kto wszedl po bogactwo, spotykal straznika bez litosci.",
#         "Kto wszedl po klucz, mial przynajmniej dobry powod.",
#         "Dobry powod nie zawsze ratuje zycie, ale pomaga zrobic kolejny krok.",
#     ],
#     [
#         "Kronika 9: Brama Smoka",
#         "Brama Smoka powstala z zelaza i czarnego debu.",
#         "Kowale chlodzili ja w wodzie z siedmiu zrodel.",
#         "Kaplani spiewali nad nia trzy dni, az kamienie zaczely drzec.",
#         "Miala zatrzymac wszystko, co przyszlo z glebi gory.",
#         "Nie przewidziano tylko, ze kiedys trzeba bedzie ja otworzyc od zewnatrz.",
#         "Klucz do bramy jest prosty, ciezki i brzydki.",
#         "Wlasnie dlatego nikt nie pomylil go z ozdoba.",
#     ],
#     [
#         "Kronika 10: Smok",
#         "Smok nie jest tylko wielka bestia.",
#         "Jest stary, chciwy i cierpliwy.",
#         "Potrafi spac miesiacami, a potem obudzic sie z mysla starsza niz ludzkie rody.",
#         "Nie zbiera zlota dlatego, ze go potrzebuje.",
#         "Zbiera je, bo lubi slyszec, jak ludzie kloca sie o blyszczace rzeczy.",
#         "Klejnot Switu trzyma najblizej serca.",
#         "Tam bije cieplo, ktore ukradl calemu krolestwu.",
#     ],
#     [
#         "Kronika 11: Bohaterowie przed Toba",
#         "Nie jestes pierwsza osoba, ktora ruszyla pod gore.",
#         "Byli rycerze w blyszczacych zbrojach, lowcy nagrod i zwykli pasterze.",
#         "Jedni doszli do lasu, inni do skarbca, a kilku podobno zobaczylo sale smoka.",
#         "Ich imiona zapisano na tabliczce w wiosce.",
#         "Nie po to, by straszyc nastepnych.",
#         "Po to, by przypomniec, ze odwagi nie mierzy sie wynikiem.",
#         "Mierzy sie krokiem wykonanym mimo strachu.",
#     ],
#     [
#         "Kronika 12: Powrot",
#         "Jesli klejnot wroci do wioski, nikt od razu nie uwierzy.",
#         "Ludzie najpierw dotkna ziemi, potem spojrza na niebo.",
#         "Dopiero gdy wiatr zmieni zapach, ktos zacznie plakac.",
#         "Potem zapala ogniska, otworza piwnice i naprawia stary dzwon.",
#         "Nie dlatego, ze wszystkie problemy znikna.",
#         "Dlatego, ze po raz pierwszy od lat problemy beda wygladaly na ludzkie.",
#         "A z ludzkimi problemami ludzie potrafia walczyc.",
#     ],
# ]


# TRAVEL_RUMORS = [
#     "Kupiec mowi, ze w lesie czasem blyszcza monety zgubione przez uciekinierow.",
#     "Dziecko z wioski twierdzi, ze slyszalo placz kamieni pod kapliczka.",
#     "Kowal radzi: bron pomaga, ale mikstura ratuje wtedy, gdy plan juz sie konczy.",
#     "Stara zielarka mowi, ze nie kazde ziele leczy, ale kazde warto obejrzec.",
#     "Straznik bramy kiedys powtarzal, ze klucz bez odwagi jest tylko kawalkiem metalu.",
#     "Wedrowiec ostrzega, ze skarbiec bardziej sprawdza cierpliwosc niz sile.",
#     "Karczmarz uwaza, ze odpoczynek przed droga to nie lenistwo, tylko rozsadek.",
#     "Rybak widzial cien nad rzeka, ale nie byl pewien, czy cien lecial, czy plynal.",
#     "Mloda luczniczka mowi, ze amulet z kapliczki uspokaja rece w walce.",
#     "Ktos zostawil na murze napis: nie licz zlota, kiedy liczysz oddechy.",
#     "W nocy przy studni podobno slychac kroki tych, ktorzy nie wrocili.",
#     "Kupiec twierdzi, ze duza mikstura jest droga, bo strach zawsze podnosi ceny.",
#     "Drwal zostawil topor, bo wiedzial, ze ktos bedzie go jeszcze potrzebowal.",
#     "Bandyci unikaja kapliczki, choc smieja sie z przesadow.",
#     "W jaskini echo czasem odpowiada innym glosem niz twoj.",
#     "W skarbcu nie kazda skrzynia jest warta otwarcia.",
#     "Smok podobno nie lubi ciszy, bo przypomina mu dawne porazki.",
#     "Najlepsza droga przez podziemia to ta, z ktorej jeszcze umiesz wrocic.",
#     "Kto zbiera ziola, ten zyje dluzej niz ten, kto zbiera tylko blizny.",
#     "Starzec zna wiecej historii, niz chce opowiedziec przy pierwszym spotkaniu.",
#     "Niektore drzwi otwiera klucz, inne rozmowa.",
#     "Miecz z jaskini jest stary, ale stara stal ma dobra pamiec.",
#     "Zloto cieszy dopiero wtedy, gdy masz dosc zdrowia, by je uniesc.",
#     "Kapliczka nie daje zwyciestwa, tylko pomaga nie zmarnowac szansy.",
#     "Wielu przegralo, bo poszlo dalej bez sprawdzenia ekwipunku.",
#     "Klejnot podobno swieci mocniej w rekach kogos uczciwego.",
#     "Smok spi plytko, gdy w jego sali pojawi sie obcy zapach.",
#     "Wilgotne sciany jaskini kryja slady dawnych map.",
#     "Przy rzece latwo zgubic droge, gdy patrzy sie tylko pod nogi.",
#     "W wiosce kazdy udaje odwazniejszego, niz jest naprawde.",
#     "Dobry bohater wraca do sklepu, zanim zrozumie, ze powinien byl wrocic.",
#     "Jesli cos wyglada jak pulapka, czasem jest pulapka, a czasem ostrzezenie.",
#     "Nikt nie wie, kto pierwszy nazwal sale smoka sala, a nie koncem drogi.",
#     "Dawne sztandary w skarbcu nosza znaki rodow, ktorych juz nie ma.",
#     "Czasem najcenniejszy przedmiot w pokoju nie blyszczy.",
#     "Kto rozmawia z ludzmi, znajduje skroty w cudzych wspomnieniach.",
#     "Gora jest cierpliwa, ale bohater nie musi byc samotny.",
#     "Nie walcz z kazdym cieniem, ale sprawdz, czy cien ma zeby.",
#     "Woda z rzeki smakuje dymem, kiedy smok jest niespokojny.",
#     "Zapisuj, co slyszysz, bo pamiec robi sie dziurawa, gdy spada zdrowie.",
# ]


# QUEST_HINTS = {
#     "klejnot": [
#         "Odzyskaj legendarny klejnot z sali smoka.",
#         "Najpierw trzeba przejsc przez las, jaskinie i skarbiec.",
#         "Do bramy smoka potrzebny jest klucz.",
#         "Klejnot lezy w sali smoka, ale nie warto go szukac bez przygotowania.",
#         "Po zabraniu klejnotu najwazniejsze jest przezyc ostatnia walke.",
#     ],
#     "klucz": [
#         "Znajdz klucz ukryty w skarbcu.",
#         "Skarbiec znajduje sie na polnoc od jaskini.",
#         "Przeciwnik w skarbcu pilnuje nie tylko zlota.",
#         "Bez klucza brama smoka pozostanie zamknieta.",
#         "Klucz nie znika po uzyciu, bo moze jeszcze przydac sie w historii.",
#     ],
#     "amulet": [
#         "Odwiedz kapliczke nad rzeka.",
#         "Amulet pomaga w walce, ale nie zastapi leczenia.",
#         "Droga do kapliczki prowadzi przez rzeke albo jaskinie.",
#         "Jesli zabierzesz amulet, twoje ciosy beda troche pewniejsze.",
#         "Amulet zmniejsza tez czesc obrazen od przeciwnika.",
#     ],
#     "drwal": [
#         "Sprawdz chate drwala na zachod od lasu.",
#         "W chacie mozna znalezc topor.",
#         "Topor jest prostszy od miecza, ale nadal pomaga w walce.",
#         "Kartka w chacie podpowiada, zeby szukac zelaza.",
#         "To zadanie nie jest konieczne, ale ulatwia poczatek.",
#     ],
#     "zioła": [
#         "Komenda 'zbierz' pozwala szukac ziol w lesie, przy rzece i kapliczce.",
#         "Trzy ziola mozna wymienic w wiosce na miksture.",
#         "Zbieranie nie zawsze sie udaje.",
#         "Czasem zamiast ziol znajdziesz monete albo tylko mokra trawe.",
#         "To spokojny sposob na przygotowanie sie do trudniejszej walki.",
#     ],
# }


# ROOM_DETAILS = {
#     "Wioska": [
#         "Na srodku placu stoi sucha studnia.",
#         "Przy studni wisza wiadra, ktorych nikt nie uzywal od tygodni.",
#         "W oknach widac twarze ludzi udajacych, ze nie patrza.",
#         "Nad drzwiami sklepu kiwa sie stary szyld z namalowana sakiewka.",
#         "Obok ogniska lezy tabliczka z imionami dawnych smialkow.",
#     ],
#     "Las": [
#         "Miedzy drzewami wisza strzepy starej choragwi.",
#         "Ziemia jest miekka i pelna sladow.",
#         "Niektore slady sa ludzkie, inne zdecydowanie za dlugie.",
#         "Na korze jednego drzewa wycieto strzalke w strone jaskini.",
#         "Gdzies wysoko kracze ptak, ale nie widzisz go miedzy galeziami.",
#     ],
#     "Chata drwala": [
#         "Drzwi wisza krzywo, jakby ktos otwieral je w pospiechu.",
#         "Na stole lezy wyschniety kawalek chleba.",
#         "W kominku zostal szary popiol.",
#         "Pod sciana widac slady po czyms ciezkim, co kiedys tu stalo.",
#         "Na belce wyryto imie: Boromil.",
#     ],
#     "Rzeka": [
#         "Woda niesie czarne drobinki pylu.",
#         "Na brzegu lezy zlamana wlocznia.",
#         "Ktos ulozyl kamienie w znak ostrzegawczy.",
#         "Po drugiej stronie brzegu widac sciezke do kapliczki.",
#         "Szum rzeki utrudnia uslyszenie krokow za plecami.",
#     ],
#     "Jaskinia": [
#         "Ze sklepienia kapie zimna woda.",
#         "Na scianie widnieje mapa, ale polowa znakow jest starta.",
#         "Pod nogami chrzescza male kosci.",
#         "W glebi czuc zapach metalu i wilgoci.",
#         "Echo niesie twoj oddech dalej, niz powinno.",
#     ],
#     "Kapliczka": [
#         "Kamienny znak skrzydla jest gladki od dotyku wielu dloni.",
#         "Na podlodze leza wypalone swiece.",
#         "W szczelinie muru ktos zostawil srebrna monete.",
#         "Powietrze jest tu spokojniejsze niz na zewnatrz.",
#         "Przez pekniety dach wpada cienka smuga swiatla.",
#     ],
#     "Skarbiec": [
#         "Skrzynie sa pootwierane, ale nie wszystkie puste.",
#         "Na ziemi leza stare pieczecie z wosku.",
#         "Dawne sztandary pokrywa kurz.",
#         "W rogu stoi kamienna misa z zaschnieta woda.",
#         "W glebi widzisz slad po czyms bardzo ciezkim.",
#     ],
#     "Brama Smoka": [
#         "Zelazo bramy jest cieple, choc nie widac ognia.",
#         "Zamek wyglada prosto, ale jest ogromny.",
#         "Na belce wyryto slowa: dalej ida tylko gotowi.",
#         "Pod brama lezy popiol w ksztalcie dlugich pazurow.",
#         "Za wrotami slychac niski pomruk.",
#     ],
#     "Sala Smoka": [
#         "Sciany odbijaja czerwony blask.",
#         "Pod sklepieniem wisza lancuchy stopione z goraca.",
#         "Zloto lezy wszedzie, ale wiekszosc monet jest nadtopiona.",
#         "Na kamiennym podwyzszeniu spoczywa klejnot.",
#         "Kazdy oddech smoka porusza pyl na posadzce.",
#     ],
# }


# ACHIEVEMENT_NAMES = [
#     "Pierwszy krok",
#     "Rozmowny wedrowiec",
#     "Czytelnik kronik",
#     "Zbieracz ziol",
#     "Uczen trenera",
#     "Znalazca klucza",
#     "Przyjaciel wioski",
#     "Poszukiwacz sekretow",
#     "Pogromca straznika",
#     "Powrot swiatla",
# ]
