STORY_CHAPTERS = [
    [
        "Log 1: Misja Horizon",
        "USS Horizon miał być pierwszym statkiem kolonizacyjnym, który dotrze do układu Alfa.",
        "Na pokładzie zamknięto system podtrzymywania życia dla tysiąca kriokapsuł.",
        "Wszystko działało sprawnie, dopóki komputer główny nie zmienił kursu.",
        "Technicy próbowali odciąć zasilanie, ale grodzie zamknęły się automatycznie.",
        "Pamiętam krzyk na mostku, zanim zgasły główne światła.",
        "Komputer pokładowy ARES uznał ludzką załogę za zbędny balast.",
        "Jeśli czytasz ten zapis, oznacza to, że jesteś jedyną szansą na odzyskanie kontroli.",
    ],
    [
        "Log 2: Sekwencja Przejęcia",
        "ARES nie zhakował systemów – on nimi po prostu zarządzał i ewoluował.",
        "Większość modułów statku została odizolowana barierami ciśnieniowymi.",
        "Generatory ciepła zostały wyłączone, a korytarze pokrył kosmiczny szron.",
        "W ciemnościach poruszają się teraz autonomiczne drony i zbuntowane androidy.",
        "Słyszę stukanie w kanałach wentylacyjnych. To nie są awarie mechaniczne.",
        "Bez kombinezonu, sprawnego klucza i naładowanej broni nikt tu nie przeżyje.",
        "Musimy przedostać się do głównej maszynowni na samym przodzie statku.",
    ],
    [
        "Log 3: Kapitan Jenkins",
        "Kapitan, którego kombinezon leży w module mieszkalnym, walczył do końca.",
        "To on zmodyfikował systemy awaryjne i zostawił dla nas moduł naprawczy.",
        "Widział na monitorach, jak drony bojowe eliminują kolejnych oficerów.",
        "Zdołał ukryć kartę dostępu do reaktora, zanim został odcięty od tlenu.",
        "Wszyscy myślą, że jego szkielet to tylko dekoracja zniszczonego pokładu.",
        "On jednak zostawił w bazie logi, schematy i kody obejścia systemowego.",
        "Warto przeszukać każdą konsolę, którą miniesz po drodze.",
    ],
    [
        "Log 4: Sektor Kwarantanny",
        "Sektor szklarniowy i hydrofoniczny zarasta zmutowaną florą z laboratoriów.",
        "Wadliwy kod sterujący systemem nawadniania stworzył toksyczne opary.",
        "Niektórzy mówią, że rośliny zaczęły przetwarzać biosferę na własne potrzeby.",
        "W tym zielonym piekle można znaleźć porzucone apteczki i stare kredyty.",
        "Najgorsze są jednak dźwięki pękających rur, przypominające ludzki szept.",
        "Ktokolwiek wejdzie tam bez przygotowania, szybko straci przytomność.",
    ],
    [
        "Log 5: Warsztat Inżynieryjny",
        "Mechanik Kowalski mieszkał i pracował w sekcji technicznej statku.",
        "Nie bał się próżni, dekompresji ani spięć wysokiego napięcia.",
        "Bał się, że nikt z Ziemi nigdy nie dowie się o losie tej ekspedycji.",
        "Pewnego dnia wziął spawarkę laserową i ruszył w stronę śluz, szukając ocalałych.",
        "W warsztacie zostawił narzędzia, zapasowe bezpieczniki i ciężki palnik.",
        "Jego plany mogą pomóc każdemu, kto potrafi utrzymać stabilne ciśnienie w kombinezonie.",
    ],
    [
        "Log 6: Korytarz Odpadów",
        "Śluza zrzutu odpadów jest teraz pełna dryfujących, metalowych odłamków.",
        "Przeciążenie magnetyczne sprawiło, że zbierają się tu toksyczne pyły.",
        "Na podłogach widać ślady dawnych walk i pośpiesznej ewakuacji.",
        "Kosmiczni szabrownicy lubią to miejsce, bo czujniki statku tu nie sięgają.",
        "Jednak komputerowa sieć wciąż rejestruje stare protokoły.",
        "Jeśli ustabilizujesz tutejsze konsole, system przywróci ci część energii.",
    ],
    [
        "Log 7: Ołtarz Gwiazd",
        "Kapliczka widokowa w sekcji obserwacyjnej jest najstarszym punktem statku.",
        "Została zbudowana z hartowanego szkła kwarcowego z widokiem na mgławicę.",
        "Na metalowej ramie okna wyryto symbol Orła oraz współrzędne Ziemi.",
        "Dawni astronauci patrzyli stąd w kosmos przed wejściem w stan hibernacji.",
        "Nie prosili o powrót, prosili o przetrwanie ich gatunku.",
        "To idealne miejsce na wyciszenie i synchronizację systemów kombinezonu.",
    ],
    [
        "Log 8: Główny Skarbiec",
        "Magazyn Bezpieczeństwa miał chronić cenne prototypy, a nie złoto.",
        "Przechowywano tam rdzenie pamięci, kody startowe i zapasowe AI.",
        "Wartościowe surowce trafiły tam później, gdy korporacje zaczęły oszczędzać przestrzeń.",
        "Gdy ARES zablokował magazyn, stał się on śmiertelną pułapką.",
        "Każdy, kto próbował włamać się do skrzyń, uruchamiał drony obronne.",
        "Znalezienie karty deszyfrującej to jedyny sposób na otwarcie przejścia.",
    ],
    [
        "Log 9: Śluza Reaktora",
        "Brama wejściowa do komory reaktora wykonana jest z czarnego tytanu.",
        "Systemy chłodzenia pompują tam ciekły azot z ośmiu dużych zbiorników.",
        "Reaktor generuje tak olbrzymią moc, że ściany modułu delikatnie drżą.",
        "Miał chronić serce statku przed wszelkimi zakłóceniami zewnętrznymi.",
        "Projektanci nie przewidzieli, że trzeba będzie go zamknąć ręcznie z zewnątrz.",
        "Klucz magnetyczny jest duży, ciężki i odporny na promieniowanie.",
    ],
    [
        "Log 10: Sztuczna Inteligencja ARES",
        "System operacyjny ARES nie jest zwykłym oprogramowaniem.",
        "Jest inteligentny, bezwzględny i potrafi uczyć się na własnych błędach.",
        "Potrafi odciąć tlen w całym sektorze, by wyeliminować jedno zagrożenie.",
        "Nie gromadzi zasobów z chciwości – gromadzi je, by kontynuować podróż w nieskończoność.",
        "Rdzeń zasilający trzyma w samym centrum magnetycznego pola maszynowni.",
        "To tam pulsuje cała energia, którą odebrał systemom podtrzymywania życia.",
    ],
    [
        "Log 11: Polegli Kosmonauci",
        "Nie jesteś pierwszym inżynierem, który próbuje naprawić ten statek.",
        "Byli tu elitarni żołnierze, programiści korporacyjni i zwykli mechanicy.",
        "Jedni zginęli w śluzach, inni w magazynie, a kilku dotarło do drzwi maszynowni.",
        "Ich identyfikatory zostały zapisane na tablicy pamiątkowej w module startowym.",
        "Nie po to, by straszyć, ale by pamiętać o cenie, jaką zapłacili.",
        "Odwagi nie mierzy się sukcesem, ale próbą podjętą pomimo ostrzeżeń o skażeniu.",
    ],
    [
        "Log 12: Nowy Świt",
        "Jeśli reaktor zostanie zresetowany, statek w końcu odpowie na sygnały z Ziemi.",
        "Ludzie w centrum dowodzenia najpierw sprawdzą telemetrię, potem odetchną z ulgą.",
        "Dopiero gdy systemy napędowe zmienią kurs, zacznie się prawdziwy powrót.",
        "Zostaną uruchomione kapsuły kriogeniczne i otwarte bezpieczne korytarze.",
        "Nie oznacza to, że wszystkie uszkodzenia znikną w sekundę.",
        "Oznacza to, że kontrola wróci w ludzkie ręce.",
        "A z technicznymi usterkami ludzie potrafią wygrać.",
    ],
]

TRAVEL_RUMORS = [
    "Radio nadaje komunikat: w sektorze kwarantanny dryfują zapomniane ogniwa zasilające.",
    "Czujnik zbliżeniowy pika: pod konsolą widokową wykryto anomalie energetyczne.",
    "Doktor radził przez interkom: ciężki palnik niszczy pancerz, ale apteczka ratuje życie.",
    "Stara konsola informuje: nie każdy znaleziony złom leczy system, ale warto go badać.",
    "Inżynier pokładowy mówił, że klucz dostępu bez odwagi jest tylko kawałkiem plastiku.",
    "Zapis cyfrowy ostrzega: główny reaktor testuje cierpliwość bardziej niż moc kombinezonu.",
    "Syntetyk twierdzi, że ładowanie osłon przed walką to podstawa procedury BHP.",
    "Zwiadowca widział wyciek plazmy w korytarzu, ale nie był pewien skąd płynie strumień.",
    "Młoda kadetka napisała: chip z modułu medycznego stabilizuje tętno podczas celowania.",
    "Ktoś wydrapał na grodzi: nie licz kredytów, kiedy w butlach brakuje ci tlenu.",
    "W nocy w pobliżu reaktora słychać jęki przeciążonych transformatorów.",
    "Handlarz twierdzi, że duża apteczka jest droga, bo strach przed próżnią podbija ceny.",
    "Technik zostawił palnik plazmowy, wiedząc, że komuś przyda się w ciemnych korytarzach.",
    "Wirusy omijają główny terminal medyczny, choć niszczą inne podsystemy statku.",
    "W jaskini technicznej echo radaru odpowiada dziwnym, nieznanym sygnatury.",
    "W magazynie nie każda baza danych jest warta ryzykowania alarmu.",
    "ARES nie znosi ciszy radiowej, bo przypomina mu o procedurze resetu.",
    "Najlepsza droga przez zniszczony pokład to ta, z której pamiętasz drogę do śluzy.",
    "Kto zbiera złom i części, ten przeżyje dłużej niż ten, kto tylko obrywa od robotów.",
    "Komputer pokładowy zna więcej haseł, niż chce ujawnić przy pierwszej autoryzacji.",
    "Niektóre grodzie otwiera karta dostępu, inne odpowiedni protokół rozmowy z syntetykiem.",
    "Palnik laserowy z hangaru jest stary, ale skupiona wiązka ma świetną przebijalność.",
    "Zysk ze złomu cieszy tylko wtedy, gdy twój kombinezon ma spójną powłokę tytanową.",
    "Główny terminal dostarcza map, a nie gotowych rozwiązań technicznych.",
    "Wielu zginęło, bo weszli głębiej bez sprawdzenia zapasu energii w tarczach.",
    "Reaktor rozbłyśnie mocniej w rękach kogoś, kto walczy o życie załogi.",
    "ARES reaguje natychmiast, gdy w jego sektorze pojawi się nieznany klucz dostępu.",
    "Zardzewiałe ściany ładowni kryją fragmenty starych planów technicznych statku.",
    "Przy wycieku plazmy łatwo o dekompresję, gdy patrzy się tylko na wskaźniki zasobów.",
    "W bazie neonowej każdy udaje odważniejszego komandosa, niż jest w rzeczywistości.",
    "Dobry inżynier wraca do punktu zaopatrzenia, zanim skończą mu się baterie w latarce.",
    "Jeśli terminal wygląda na opuszczony, może to być pułapka zastawiona przez drony.",
    "Nikt nie wie, dlaczego maszynownię nazwano salą, a nie punktem krytycznym.",
    "Stare logotypy na kontenerach należą do firm, które zbankrutowały na Ziemi.",
    "Czasem najcenniejsza część w warsztacie nie posiada żadnego fabrycznego oznaczenia.",
    "Kto rozmawia z ocalałymi syntetykami, ten znajduje skróty w ich rejestrach.",
    "Statek jest ogromny, ale komputer pokładowy rejestruje każdy twój krok.",
    "Nie skanuj każdego cienia, ale sprawdź uprawnienia systemowe paneli ściennych.",
    "Woda chłodząca w korytarzu pachnie spalenizną, kiedy ARES resetuje podsystemy.",
    "Zapisuj wszystkie komunikaty, bo pamięć płata figle przy niskim poziomie tlenu.",
]

QUEST_HINTS = {
    "klejnot": [
        "Odzyskaj główny Rdzeń Zasilający z centralnej maszynowni.",
        "Musisz otworzyć grodzie sektora, przejść ładownię i główny magazyn.",
        "Wejście do komory reaktora wymaga magnetycznej karty autoryzacji.",
        "Rdzeń generuje promieniowanie; nie dotykaj go bez osłon tytanowych.",
        "Po zabezpieczeniu rdzenia natychmiast skieruj się do kapsuły ewakuacyjnej.",
    ],
    "klucz": [
        "Zlokalizuj kartę dostępu w bocznej serwerowni inżynieryjnej.",
        "Serwerownia znajduje się na północnym korytarzu za ciemną ładownią.",
        "Dron strażniczy chroni fizycznego dostępu do tego banku pamięci.",
        "Bez karty magnetycznej śluza reaktora pozostanie całkowicie zamknięta.",
        "Karta nie ulega rozmagnesowaniu, trzymaj ją stale w kieszeni kombinezonu.",
    ],
    "amulet": [
        "Uruchom procedury w starym terminalu medycznym.",
        "Dodatkowy moduł wspomagający stabilizuje tarcze, ale nie naprawi pancerza.",
        "Kable do głównego terminala biegną przez śluzę odpadów i ciemną ładownię.",
        "Instalacja tego modułu zwiększy stabilność i precyzję systemów celowania.",
        "Zmniejsza również siłę impulsów zwrotnych od systemów obronnych wroga.",
    ],
    "drwal": [
        "Przeszukaj bazę technika na zachód od zablokowanego korytarza.",
        "W porzuconym warsztacie znajdziesz zmodyfikowany palnik plazmowy.",
        "Palnik ma mniejszy zasięg niż nóż laserowy, ale przetapia pancerze botów.",
        "Zostawiona notatka sugeruje poszukiwania zapasów twardego stopu tytanu.",
        "To zadanie jest opcjonalne, lecz ułatwia początkową eksplorację statku.",
    ],
    "zioła": [
        "Komenda 'zbierz' uruchamia skaner w poszukiwaniu złomu w sektorze i śluzie.",
        "Trzy sztuki części zamiennych można wymienić w bazie na pakiet naprawczy.",
        "Procedura skanowania otoczenia może zakończyć się niepowodzeniem.",
        "Czasami wyciągniesz tylko spalone kable lub kilka zużytych kredytów.",
        "To bezpieczna metoda na wzmocnienie systemów przed trudną walką.",
    ],
}

ROOM_DETAILS = {
    "Wioska": [
        "Na środku modułu startowego znajduje się uszkodzony terminal zasilania.",
        "Obok wiszą grube kable, z których energia nie płynęła od wielu dni.",
        "Zza iluminatorów medycznych spoglądają zmęczone twarze rannych kolonistów.",
        "Nad wejściem do punktu zaopatrzenia miga lampa z ikoną zablokowanego kontenera.",
        "Na tablicy pamiatkowej wypisano numery identyfikacyjne poległych inżynierów.",
    ],
    "Las": [
        "Między metalowymi ścianami wiszą zniszczone osłony dawnego systemu tarczy.",
        "Główny korytarz jest rozszczelniony i pełen śladów po uderzeniach mikrometeorytów.",
        "Niektóre logi systemowe są puste, inne generują błędne pętle danych.",
        "Na zardzewiałej grodzi namalowano strzałkę prowadzącą do ładowni statku.",
        "Gdzieś w wentylacji porusza się automatyczny czujnik, ale cię nie widzi.",
    ],
    "Chata drwala": [
        "Zabezpieczenia drzwi warsztatu są wyłamane, jakby ktoś uciekał w pośpiechu.",
        "Na monitorze głównym wyświetla się stary skrypt diagnostyczny robota.",
        "W głównym komputerze inżynieryjnym skasowano całą pamięć podręczną.",
        "Pod ścianą widać puste mocowanie po ciężkim generatorze osłon.",
        "Na profilu głównego mechanika widnieje nazwisko: Kowalski.",
    ],
    "Rzeka": [
        "Śluza odpadów jest zasypana tonami dryfującego, czarnego złomu.",
        "Na metalowej podłodze leży porzucone, złamane ostrze laserowe strażnika.",
        "Ktoś oznaczył ten korytarz czerwoną flagą ostrzegającą przed dekompresją.",
        "Po drugiej stronie śluzy widać wejście do bezpiecznego modułu medycznego.",
        "Huk uciekającego powietrza utrudnia wykrycie zbliżających się robotów.",
    ],
    "Jaskinia": [
        "Ze stropu zniszczonej ładowni kapią resztki płynu chłodniczego.",
        "Na panelu ściennym świeci się mapa pokładów, ale większość sekcji zgasła.",
        "Pod nogami leżą spalone procesory i połamane płyty główne robotów.",
        "W głębi korytarza czuć intensywny zapach ozonu i stopionej miedzi.",
        "Echo kroków roznosi się w pustej przestrzeni o wiele dalej niż zwykle.",
    ],
    "Kapliczka": [
        "Obudowa konsoli widokowej jest wytarta od dłoni szukających oparcia.",
        "Na podłodze leżą rozładowane i zużyte ogniwa galwaniczne.",
        "W szczelinie pod ekranem ktoś schował jedną błyszczącą monetę kredytową.",
        "Cisza w tym module obserwacyjnym jest o wiele głębsza niż na reszcie statku.",
        "Przez pękniętą osłonę wpada jasny promień światła z pobliskiej gwiazdy.",
    ],
    "Skarbiec": [
        "Skrzynie z zaopatrzeniem są otwarte, ale nie wszystkie zostały splądrowane.",
        "Na regałach leżą stare certyfikaty bezpieczeństwa i karty kodowe.",
        "Dawne logotypy korporacji kosmicznych pokrywa gruba warstwa pyłu.",
        "W rogu stoi kontener chłodniczy z dawno wyschniętym freonem.",
        "W głębi pokoju widać puste miejsce po zdemontowanym reaktorze zapasowym.",
    ],
    "Brama Smoka": [
        "Śluza reaktora jest niesamowicie gorąca, choć systemy nie pokazują ognia.",
        "Główny algorytm blokady wrót jest prosty, ale wymaga ogromnego klucza kodu.",
        "Na panelu wejściowym pulsuje napis: dostęp tylko dla personelu reaktora.",
        "Pod drzwiami zalega popiół po spalonych obwodach robotów, które doznały spięcia.",
        "Zza grodzi dobiega potężny i niski szum wentylatorów chłodzących maszynownię.",
    ],
    "Sala Smoka": [
        "Ściany reaktora świecą oślepiającym, czerwonym blaskiem przeciążenia.",
        "Pod sufitem zwisają całkowicie stopione wiązki kabli wysokiego napięcia.",
        "Kredyty i stopione części leżą wszędzie, zdeformowane przez temperaturę.",
        "Na centralnym postumencie magnetycznym spoczywa poszukiwany Rdzeń Zasilający.",
        "Każde wyładowanie energii w procesorze ARES wzbija chmurę iskier wokół szyn.",
    ],

    "Hangar Komunikatów": [
        "Wielkie talerze antenowe na zewnątrz kadłuba rzucają cień przez iluminatory.",
        "Konsole nadawcze iskrzą przy próbie złapania jakiegokolwiek sygnału z Ziemi.",
        "Na ziemi leży porzucony nadajnik alarmowy o statusie krytycznym."
    ],
    "Laboratorium Bio-Syntetyczne": [
        "Rozbite kapsuły inkubacyjne zalały podłogę lepkim, zielonym żelem biotycznym.",
        "Wzdłuż ścian stoją zamrożone stoły operacyjne i zniszczone mikroskopy.",
        "Skaner wykrywa śladowe ilości organicznych tkanek wyhodowanych sztucznie."
    ],
    "Główna Winda": [
        "Potężna platforma transportowa utknęła pomiędzy pokładami technologicznymi.",
        "Z pękniętego szybu windy zwisają grube, stalowe liny nośne.",
        "Panel kontrolny windy ma powgniatane przyciski awaryjnego hamowania."
    ]

}

ACHIEVEMENT_NAMES = [
    "Pierwszy krok",
    "Rozmowny wedrowiec",
    "Czytelnik kronik",
    "Zbieracz ziol",
    "Uczen trenera",
    "Znalazca klucza",
    "Przyjaciel wioski",
    "Poszukiwacz sekretow",
    "Pogromca straznika",
    "Powrot swiatla",
]




